<?php

$_DEFAULT_CONFIG = (object)[
	'modules' => [],
	'database' => [
		'engine' => 'none',
		'hostname' => '',
		'port'     => '',
		'username' => '',
		'database' => '',
		'password' => '',
		'slavedb'  => false,
		'slavedb_config' => [
			'only_master'        => false,
			'master_for_reads'   => false,
			'master_probability' => 0,
			'slaves' => [
				['hostname' => 'dbslave01', 'probability' => 1],
				['hostname' => 'dbslave02', 'probability' => 1],
			],
		],
		'citusdb'  => false,
		'citusdb_replicas' => 2,
		'citusdb_shard_size' => '1GB',
		'citusdb_config' => [
			'time_based_table' => [
				'distribution_type'  => 'append',
				'distribution_field' => 'timestamp',
			],
			'hash_table' => [
				'distribution_type'  => 'hash',
				'distribution_field' => 'unique_id',
				'num_shards'         => 256,
			],
		],
	],
	'default_site' => [
		'email_addresses' => [
			'from' => 'info@example.com',
			'contact_us' => 'info@example.com',
		],
		'force_email_rcpt' => FALSE,
		'default_site' => false,
		'enable_ssl' => false,
		'force_ssl' => false,
		'force_www_subdomain' => true,
		'default_block_type' => 'HTML',
		'modules' => [],
		'tmp_path' => '/tmp',
		'secret' => 'ABCDEFGHIJK1234567891234',
		'name' => 'OpenMVC',
		'namespace' => 'default',
		'editable_homepage' => false,
		'ckeditor_page_edit' => false,
		'contenttools_page_edit' => true,
		'default_layout_class' => '\\core\\classes\\renderable\\Layout',
		'default_layout_template' => 'layouts/default.php',
		'admin_layout_class' => '\\core\\classes\\renderable\\Layout',
		'admin_layout_template' => 'layouts/admin.php',
		'theme' => 'default',
		'static_prefix' => '/static-1',
		'og_meta_tags' => true,
		'og_type' => 'website',
		'load_default_language_files' => false,
		'enable_analytics' => true,
		'enable_analytics_ecommerce' => true,
		'enable_latex' => false,
		'enable_public' => true,
		'enable_admin' => true,
		'display_errors' => false,
		'site_offline_mode' => false,
		'site_maintenance_mode' => false,
		'post_login_redirect' => false,
		'page_class' => 'container',
		'meta_title_separator' => ' :: ',
		'bcrypt_cost' => 10,
		'logger_clean_enable' => true,
		'logger_clean_frequency' => 1000,
		'logger_clean_ttl' => 14,
		'logger_clean_regex' => '/(\d{2}-\d{2}-\d{4})\.log$/',
		'logger_clean_path' => 'logs/',
		'locale' => 'en_AU.utf8',
		'language' => 'en',
		'records_per_page' => 20,
		'num_pagination_links' => 11,
		'contact_fields' => [
			'name' => ['type'=>'string', 'message_text_tag' => 'error_name'],
			'email' => ['type'=>'email', 'message_text_tag' => 'error_email'],
			'enquiry' => ['type'=>'string', 'message_text_tag' => 'error_enquiry'],
		],
		'customer_types' => [
			1 => 'Normal',
		],
		'filemanager_paths' => [
			'/themes/default/images/' => 'images',
			'/themes/default/css/' => 'files',
			'/themes/default/js/' => 'files',
		],
	]
];
